### PR TITLE
ran make jsonnet update

### PR DESCRIPTION
**Pull request by dofinn**

### CODE REVIEW

**Comment by squat** [comment]
You'll need to run `make jsonnet-vendor` along with this bump to ensure all jsonnet code gets vendored too

**Comment by dofinn** [comment]
thanks @squat . I have executed this locally and its produced no change to PR. Leaving as is for review. I have this running my CRC if it helps using this image:

```
oc get pods                                                                              ✔  39s  observatorium/api-crc-testing:6443/kube:admin/observatorium ⎈  !4/73  
NAME                                                           READY   STATUS    RESTARTS   AGE
grafana-5b8947658c-w9v8s                                       1/1     Running   0          6h49m
observatorium-operator-6b7bdd76b5-fxtds                        1/1     Running   0          7h36m
observatorium-xyz-loki-compactor-0                             1/1     Running   0          8h
observatorium-xyz-loki-distributor-765b84479-z7wwc             1/1     Running   0          8h
observatorium-xyz-loki-ingester-0                              1/1     Running   0          8h
observatorium-xyz-loki-querier-0                               1/1     Running   0          8h
observatorium-xyz-loki-query-frontend-55947c6cd-dh2kl          1/1     Running   0          8h
observatorium-xyz-observatorium-api-67568c564c-zz4mb           1/1     Running   0          6h54m
observatorium-xyz-thanos-compact-0                             1/1     Running   0          8h
observatorium-xyz-thanos-query-6b9cf5b56-66jtj                 1/1     Running   0          8h
observatorium-xyz-thanos-query-frontend-54c7dbf8f5-wf7j5       1/1     Running   0          8h
observatorium-xyz-thanos-receive-controller-57c47d5884-vbxc5   1/1     Running   0          8h
observatorium-xyz-thanos-receive-default-0                     1/1     Running   0          8h
observatorium-xyz-thanos-rule-0                                1/1     Running   0          8h
observatorium-xyz-thanos-store-memcached-0                     2/2     Running   0          8h
observatorium-xyz-thanos-store-shard-0-0                       1/1     Running   2          8h
```

**Comment by metalmatze** [comment]
I don't see how this changes anything. What was the motivation for the bump? Happy to merge it regardless, just wondering.

**Comment by dofinn** [comment]
> "it looks like the operator repository's pinned vendor to observatorium/deployments is outdated. The loki package in our jsonnet code dropped the table_manager in favor of the compactor a while ago." 

@periklis

**Pull request closed without merging**
