### PR TITLE
Support configure resources

### PR DESCRIPTION
**Pull request by clyang82**
Enable configure resources for each component.

Signed-off-by: clyang82 <chuyang@redhat.com>

### CODE REVIEW

**Review by kakkoyun — APPROVED** [review]
LGTM. However, I have long term concerns.

First of all these reviews are getting challenging. We need to define clear ownership of this component and what we would like to achieve. We need to build context and knowledge.

Second, jsonnet files for optional attributes are getting out of control. They are cumbersome and not easy yo digest. We should come up with a better pattern.

And last we are getting reckless with the API, we just keep adding things to CRD. The existing API already seems archaic comparing our recent configuration. Moreover, we don't think about the future that we plan, we might need to rewrite the whole CRD to support other signals.

Adding my thoughts here to make them visible, these don't particular concern things introduce in this PR.

**Comment by bwplotka** [comment]
Agree with @kakkoyun. We should find a way to define way forward that does not block experimentation but doe not trash API CRD that suppose to serve some purpose

**Comment by bwplotka** [comment]
cc @paulfantom

**Comment by bwplotka** [comment]
Adde https://github.com/observatorium/operator/issues/57 @kakkoyun

**Pull request merged**
